filebeat.inputs:
- type: log
  enabled: true
  paths:
     - /var/cvs/2015_2018.csv
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
output.logstash:
  enabled: true
  hosts: ["Logstash-Filebeat:9704"]
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

